const paragraphs = [
    "A Hunter went out after game, and succeeded in catching a hare, which he was carrying home with him when he met a man on horseback, who said to him, You have had some sport I see, sir, and offered to buy it. The Hunter readily agreed; but the Horseman had no sooner got the hare in his hands than he set spurs to his horse and went off at full gallop. The Hunter ran after him for some little distance; but it soon dawned upon him that he had been tricked, and he gave up trying to overtake the Horseman, and, to save his face, called after him as loud as he could, All right, sir, all right, take your hare: it was meant all along as a present.",
    "A Widow, thrifty and industrious, had two servants, whom she kept pretty hard at work. They were not allowed to lie long abed in the mornings, but the old lady had them up and doing as soon as the cock crew. They disliked intensely having to get up at such an hour, especially in winter-time: and they thought that if it were not for the cock waking up their Mistress so horribly early, they could sleep longer. So they caught it and wrung its neck. But they weren't prepared for the consequences. For what happened was that their Mistress, not hearing the cock crow as usual, waked them up earlier than ever, and set them to work in the middle of the night.",
    "A certain man hired an Ass for a journey in summertime, and started out with the owner following behind to drive the beast. By and by, in the heat of the day, they stopped to rest, and the traveller wanted to lie down in the Ass's Shadow; but the owner, who himself wished to be out of the sun, wouldn't let him do that; for he said he had hired the Ass only, and not his Shadow: the other maintained that his bargain secured him complete control of the Ass for the time being. From words they came to blows; and while they were belabouring each other the Ass took to his heels and was soon out of sight.",
    "One hot and thirsty day in the height of summer a Lion and a Boar came down to a little spring at the same moment to drink. In a trice they were quarrelling as to who should drink first. The quarrel soon became a fight and they attacked one another with the utmost fury. Presently, stopping for a moment to take breath, they saw some vultures seated on a rock above evidently waiting for one of them to be killed, when they would fly down and feed upon the carcase. The sight sobered them at once, and they made up their quarrel, saying, We had much better be friends than fight and be eaten by vultures.",
    "A Tortoise, discontented with his lowly life, and envious of the birds he saw disporting themselves in the air, begged an Eagle to teach him to fly. The Eagle protested that it was idle for him to try, as nature had not provided him with wings; but the Tortoise pressed him with entreaties and promises of treasure, insisting that it could only be a question of learning the craft of the air. So at length the Eagle consented to do the best he could for him, and picked him up in his talons. Soaring with him to a great height in the sky he then let him go, and the wretched Tortoise fell headlong and was dashed to pieces on a rock.",
    "A Man while going through the fields along his solitary path, heard the word Hail! whereat he stopped for a moment, but seeing no one, went on his way. Again the same sound saluted him from a hidden spot; encouraged by the hospitable voice, he stopped short, that whoever it was might receive the like civility. When, looking all about, he had remained long in perplexity, and had lost the time in which he might have walked some miles, a Raven showed himself, and hovering above him, continually repeated Hail! Then, perceiving that he had been deluded: Perdition seize you, said he, most mischievous bird, to have thus delayed me when I was in such a hurry.",
    "A Hunter went out after game, and succeeded in catching a hare, which he was carrying home with him when he met a man on horseback, who said to him, You have had some sport I see, sir, and offered to buy it. The Hunter readily agreed; but the Horseman had no sooner got the hare in his hands than he set spurs to his horse and went off at full gallop. The Hunter ran after him for some little distance; but it soon dawned upon him that he had been tricked, and he gave up trying to overtake the Horseman, and, to save his face, called after him as loud as he could, All right, sir, all right, take your hare: it was meant all along as a present.",
    "A Widow, thrifty and industrious, had two servants, whom she kept pretty hard at work. They were not allowed to lie long abed in the mornings, but the old lady had them up and doing as soon as the cock crew. They disliked intensely having to get up at such an hour, especially in winter-time: and they thought that if it were not for the cock waking up their Mistress so horribly early, they could sleep longer. So they caught it and wrung its neck. But they weren't prepared for the consequences. For what happened was that their Mistress, not hearing the cock crow as usual, waked them up earlier than ever, and set them to work in the middle of the night.",
    "A certain man hired an Ass for a journey in summertime, and started out with the owner following behind to drive the beast. By and by, in the heat of the day, they stopped to rest, and the traveller wanted to lie down in the Ass's Shadow; but the owner, who himself wished to be out of the sun, wouldn't let him do that; for he said he had hired the Ass only, and not his Shadow: the other maintained that his bargain secured him complete control of the Ass for the time being. From words they came to blows; and while they were belabouring each other the Ass took to his heels and was soon out of sight.",
    "One hot and thirsty day in the height of summer a Lion and a Boar came down to a little spring at the same moment to drink. In a trice they were quarrelling as to who should drink first. The quarrel soon became a fight and they attacked one another with the utmost fury. Presently, stopping for a moment to take breath, they saw some vultures seated on a rock above evidently waiting for one of them to be killed, when they would fly down and feed upon the carcase. The sight sobered them at once, and they made up their quarrel, saying, We had much better be friends than fight and be eaten by vultures.",
    "A Tortoise, discontented with his lowly life, and envious of the birds he saw disporting themselves in the air, begged an Eagle to teach him to fly. The Eagle protested that it was idle for him to try, as nature had not provided him with wings; but the Tortoise pressed him with entreaties and promises of treasure, insisting that it could only be a question of learning the craft of the air. So at length the Eagle consented to do the best he could for him, and picked him up in his talons. Soaring with him to a great height in the sky he then let him go, and the wretched Tortoise fell headlong and was dashed to pieces on a rock.",
    "A Man while going through the fields along his solitary path, heard the word Hail! whereat he stopped for a moment, but seeing no one, went on his way. Again the same sound saluted him from a hidden spot; encouraged by the hospitable voice, he stopped short, that whoever it was might receive the like civility. When, looking all about, he had remained long in perplexity, and had lost the time in which he might have walked some miles, a Raven showed himself, and hovering above him, continually repeated Hail! Then, perceiving that he had been deluded: Perdition seize you, said he, most mischievous bird, to have thus delayed me when I was in such a hurry.",





];